const CREATE_PRODUCT = 'CREATE_PRODUCT'
const READ_PRODUCT = 'READ_PRODUCT'
const UPDATE_PRODUCT = 'UPDATE_PRODUCT'
const DELETE_PRODUCT = 'DELETE_PRODUCT'
const MOVE_LIST_PRODUCT = 'MOVE_LIST_PRODUCT'
const MOVE_CART_PRODUCT = 'MOVE_CART_PRODUCT'

export{
    CREATE_PRODUCT,
    READ_PRODUCT,
    UPDATE_PRODUCT,
    DELETE_PRODUCT,
    MOVE_LIST_PRODUCT,
    MOVE_CART_PRODUCT
}